title:              T2H CV
email:              hthau1909@gmail.com
description:        A Blog Theme by hthau1909
author:             hthau1909
baseurl:            "/hthau1909.github.io"
url:                "https://hthau1909.github.io"

# Social Profiles
twitter_username:   
github_username:    hthau1909
facebook_username:  Huynh Tan Hau
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
